// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Log-001', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Log-001', async function() {
    await driver.get("https://dt-teamb-web.tlabdemo.com/")
    await driver.manage().window().setRect({ width: 1004, height: 708 })
    await driver.findElement(By.css(".border:nth-child(5)")).click()
    await driver.findElement(By.css(".border:nth-child(5)")).sendKeys("wandaalifh")
    await driver.findElement(By.css(".border:nth-child(1)")).click()
    await driver.findElement(By.css(".border:nth-child(1)")).sendKeys("Ikann123#")
    await driver.findElement(By.css(".bg-primary-500")).click()
    assert(await driver.switchTo().alert().getText() == "Login success")
  })
})
